//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANG = new HashSet<CHITIETDONHANG>();
        }
    
        public int MaSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public string Mau { get; set; }
        public string TenSanPham { get; set; }
        public string Anh { get; set; }
        public string MieuTa { get; set; }
        public decimal Gia { get; set; }
        public int SoLuongTrongKho { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANG { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
    }
}
